name: Delete Files From Repo

on:
  workflow_dispatch:  # manually triggered

jobs:
  clean-repo:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete everything except .github
        shell: pwsh
        run: |
          Get-ChildItem | 
              Where-Object { $_.Name.ToUpper() -notin '.GITHUB', '.GIT' } |
              ForEach-Object {
                  Write-Host $("Removing: " + $_.FullName)
                  Remove-Item -Path $_.FullName -Recurse -Force
              }

      - name: Commit and Push Changes
        shell: pwsh
        run: |
          git config user.name "astowell8"
          git config user.email "astowell8@hotmail.com"
          git add -A
          git commit -m "Deleted all files except .github" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.PAT_GH_DIFFREPO }}@github.com/${{ github.repository }}.git"

        