name: Delete Files From Repo

on:
  workflow_dispatch:  # manually triggered

jobs:
  clean-repo:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GH_DIFFREPO }}

      - name: Debug Token Use (safe)
        run: echo "Token length ${{ secrets.PAT_GH_DIFFREPO != '' && 'set' || 'empty' }}"

      - name: Delete everything except .github
        shell: pwsh
        run: |
          Get-ChildItem | 
              Where-Object { $_.Name.ToUpper() -notin '.GITHUB', '.GIT' } |
              ForEach-Object {
                  Write-Host $("Removing: " + $_.FullName)
                  Remove-Item -Path $_.FullName -Recurse -Force
              }

      - name: Commit and Push Changes
        shell: pwsh
        run: |
          git config user.name "astowell8"
          git config user.email "astowell8@hotmail.com"
          git add -A
          git commit -m "Deleted all files except .github" || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.PAT_GH_DIFFREPO }}@github.com/${{ github.repository }}.git"

      - name: Clone other repo
        shell: pwsh
        run: git clone https://x-access-token:${{ secrets.PAT_GH_DIFFREPO }}@github.com/astowell8/GH-Actions-Learn.git source-repo

      - name: Show Contents
        shell: cmd
        run: | 
          cd source-repo
          echo source repo root contents
          dir

      - name: Show Tags
        shell: cmd
        run: |
          cd source-repo
          echo if no tags are list below. This workflow will fail.
          git tag

      - name: Get Release SHA
        shell: pwsh
        run: |           
           Set-Location source-repo
           $ReleaseBranch = 'main' 
           git checkout main
           git fetch --all --tags 
           git pull           
           $currentBranch = git rev-parse --abbrev-ref HEAD           
           Write-Host Check if the branch is 'main' 
           if ($currentBranch -ne 'main') {
               Write-Host "Error: Release tags should be only published on 'main' branch." -ForegroundColor Red
               exit 1
           } else {
               Write-Host "Current branch ($currentBranch) is the designated release branch. Continueing ... " -ForegroundColor Green
           }
           $tags = ( git tag --list "Release_v[0-9]*.[0-9]*.[0-9]*" )
           #git tag --list "Release_v[0-9]*.[0-9]*.[0-9]*"
           #Write-Host $tags
           #Write-Host ("Length: " + $tags.length)
           $SortedTags = @()          
           $SortedTags = $tags | Sort-Object -Descending             
           $release = git rev-parse $SortedTags[0]
           $previous = git rev-parse $SortedTags[1]
           "release_sha=$release" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
           "previous_sha=$previous" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
           write-Host "Contents:"
           write-Host $SortedTags
           Write-Host ("Release SHA " + $release)
           Write-Host ("Previous SHA " + $release)           
#
      - name: Use the SHAs
        shell: pwsh
        run: |
          Write-Host "Release SHA: ${{ steps.get_release_sha.outputs.release_sha }}"
          Write-Host "Previous SHA: ${{ steps.sha_step.outputs.previous_sha }}"          